id: '16970609483000.2081887314926849'
name: loadDboDvfConfig
nameConfigured: true
steps:
  - id: '16970609664360.9276434014594908'
    type: LOAD_COLLECTION
    name: load
    params:
      - type: datasourceId
        value: POM_test
        valueType: string
      - type: resourceId
        value: dbo.dvfConfig
        valueType: string
      - type: filters
        value: []
        valueType: custom
      - type: ordering
        value:
          limit:
            value: 1000
          offset:
            value: ''
          orderBy:
            value: ''
          orderDirection:
            value: asc
        valueType: custom
      - type: additionalParams
        value:
          - name: ''
            value: ''
        valueType: custom
      - type: customDatabaseName
        value: '{{app.env == "prod" ? ''POM_prod'' : ''POM_test''}}'
        valueType: interpolatedValue
      - type: successMapper
        value: ''
        valueType: interpolatedValue
      - type: failureMapper
        value: ''
        valueType: interpolatedValue
      - type: mapperEnabled
        value: false
        valueType: custom
    level: 0
    fallthroughError: false
    isChanged: true
singleStep: false
mode: manual
modeConfigured: false
parentPageId: '16970600071930.3468845352422827'
folder: false
parentId: null
config:
  shouldConfirm: false
  confirmMessage: Are you sure you'd like to proceed with "{{actions.loadDboDvfConfig.name}}"?
  showSuccessToast: false
  successToast: Action "{{actions.loadDboDvfConfig.name}}" successfully executed
  successToastDuration: '3000'
  successToastHideByClick: false
  showErrorToast: true
  errorToast: Action "{{actions.loadDboDvfConfig.name}}" has failed
  errorToastDuration: '3000'
  errorToastHideByClick: false
  delay: '0'
  runWhenFirstReferenced: true
  preserveStateOnPageChange: false
assigned: false
index: 29
