storeItemList:
  - id: '17000889247240.5716578225636579'
    name: docLimit
    value: 6000
    valueType: number
    initialValue: 6000
    version: 1
  - id: '17000889612390.9624357835370032'
    name: sdgLimit
    value: 5000
    valueType: number
    initialValue: 5000
    version: 1
metadata:
  favicon: ''
  code: ''
  title: Solid OMS Demo
  description: ''
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
internalType: project
