storeItemList: []
metadata:
  favicon: ''
  code: var dbname = "POM_test";
  title: Solid OMS
  description: ''
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
internalType: project
