id: '16970590271880.5107958129506303'
definitionId: smartTable
parentSlotId: '16970590271870.09910814271154189'
styles:
  xl:
    gridItem:
      x: 0
      y: 0
      w: 16
      h: 130
  xs:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 80
properties:
  dynamicColumns:
    value: []
    dataValue: |-
      [
        { prop: 'id', type: 'number', primaryKey: true },
       'full_name',
        { prop: 'avatar', type: 'image' },
        { prop: 'email', type: 'link' },
      ]
    withData: false
  data: '{{actions.loadDboDvfConfig2.data}}'
  name: dboDvfConfigTable2
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  title: 'Konfiguration Freimachung '
  showLoading:
    withData: true
    dataValue: '{{actions.loadDboDvfConfig2.loading}}'
    value: false
  showAddAction:
    value: true
    dataValue: 'false'
    withData: false
  showEditAction:
    value: true
    dataValue: 'false'
    withData: false
  showExportAction:
    value: false
    dataValue: 'true'
    withData: false
  showReloadAction:
    value: true
    dataValue: 'false'
    withData: false
  resetActivePageOnNewData: true
  rowVariation: dense
  showFilter: true
actions:
  init: []
  smartTableCreate: []
  smartTableEdit:
    - action: '16970590271900.6701403336771616'
      paramCode: ''
      blockPageLoad: false
      index: 1
  smartTableBulkEdit: []
  smartTableDelete: []
  smartTableRowSelect: []
  smartTableRowClick: []
  smartTablePageSelect: []
  smartTableFilterChange: []
  smartTableSortChange: []
  smartTableReload: []
index: 0
slots:
  - id: '16970590271880.8589753778002172'
    name: columns
    children:
      - id: '16970590271880.12121660063997552'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString253
          prop: dvfConfigName
          primaryKey: true
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '120'
          filter: true
          title: Config Name
          decoration: null
          pinColumn: left
        index: 0
        slots: []
      - id: '16970590271880.2641365192941387'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString254
          prop: kundenid
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 1
        slots: []
      - id: '16970590271880.7372107357651314'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString255
          prop: optimierung
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '80'
          filter: true
          title: brutto/netto
          sortable: false
          alignment: center
        index: 9
        slots: []
      - id: '16970590271880.7118102652583047'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString256
          prop: einlieferungplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '80'
          filter: true
          title: Einl-PLZ
          alignment: center
        index: 4
        slots: []
      - id: '16970590271880.9955124800781605'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 11
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString257
          prop: einlieferungsstelle
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '80'
          filter: true
          title: Einl-Stelle
        index: 5
        slots: []
      - id: '16970590271880.12569325082154048'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString258
          prop: absender
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '100'
          filter: true
          alignment: center
        index: 6
        slots: []
      - id: '16970590271880.3968239703147505'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString259
          prop: einlieferer
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '100'
          filter: true
          alignment: center
        index: 7
        slots: []
      - id: '16970590271880.9688247133743182'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: false
            fontSize:
              customValue: 10
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString260
          prop: preadrvariante
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '60'
          filter: true
        index: 16
        slots: []
      - id: '16970590271880.485142216844318'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: false
            fontSize:
              customValue: 10
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString261
          prop: preadrid
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '40'
          filter: true
        index: 15
        slots: []
      - id: '16970590271880.7453271425240671'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString262
          prop: kilotarif
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '80'
          filter: true
          title: Kilotarif
          alignment: center
        index: 8
        slots: []
      - id: '16970590271880.6875902949724235'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString263
          prop: sendungsart
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          alignment: center
        index: 3
        slots: []
      - id: '16970590271880.16943027339567296'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString264
          prop: image
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '40'
          filter: true
        index: 12
        slots: []
      - id: '16970590271880.45357500728109423'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString265
          prop: kuinfofestepos
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '40'
          filter: true
        index: 14
        slots: []
      - id: '16970590271880.03681627948811084'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString266
          prop: labelout
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '40'
          filter: true
        index: 13
        slots: []
      - id: '16970590271880.07510190377144754'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString267
          prop: brief_nat_ekp
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 17
        slots: []
      - id: '16970590271880.6341126821936467'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString268
          prop: brief_nat_verfahren
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 18
        slots: []
      - id: '16970590271880.6642968782176766'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString269
          prop: brief_nat_teilnahme
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 19
        slots: []
      - id: '16970590271880.8158544118081816'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
            visible: true
        properties:
          name: atomicString270
          prop: checkplz
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Check PLZ
          primaryKey: false
          filter: true
          width: '80'
          pinColumn: ''
          alignment: center
        index: 10
        slots: []
      - id: '16970590271880.5093280043072721'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
            visible: true
        properties:
          name: atomicString271
          prop: datamatrix
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Datamatrix
          primaryKey: false
          filter: true
          width: '40'
          alignment: center
        index: 11
        slots: []
      - id: '16970590271880.6717847554295473'
        definitionId: atomicString
        parentSlotId: '16970590271880.8589753778002172'
        styles:
          xl:
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
            visible: true
        properties:
          name: atomicString272
          prop: einldatum
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Einl-Datum
          primaryKey: false
          filter: true
          width: '80'
          alignment: center
        index: 2
        slots: []
