id: '16927435997720.5377202849286853'
definitionId: form
parentSlotId: '16927425039240.12205903860312306'
styles:
  xl:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 17
  xs:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 17
properties:
  dynamicFields:
    value: []
    dataValue: |-
      [
        { prop: 'id', type: 'number', primaryKey: true },
       'full_name',
        { prop: 'avatar', type: 'image' },
        { prop: 'email', type: 'link' },
      ]
    withData: false
  entity: |
    {{ui.dboDvfConfigTable.selectedRow.data}}
  name: dbodvfconfigtableForm4
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  title: Fracht (DHL)
  columns: '2'
actions:
  init: []
  submitEvent: []
  formClick: []
  changeEvent: []
  customButtonClick: []
index: 0
slots:
  - id: '16927435997720.7686952210888576'
    name: structure
    children:
      - id: '16927435997720.5708306059135495'
        definitionId: atomicString
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 16
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
            color:
              value: primary
              dataValue: basic
              withData: false
        properties:
          name: atomicString173
          prop: dvfConfigName
          primaryKey: true
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Config Name
          forceView: true
          textStyle:
            transform: none
            styles:
              - bold
        parentSlotId: '16927435997720.7686952210888576'
        index: 0
        slots: []
      - id: '16927435997720.23885694023129234'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString174
          prop: kunde
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 1
        slots: []
      - id: '16927435997720.9173633889062216'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString175
          prop: optimierung
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: brutto/netto
        parentSlotId: '16927435997720.7686952210888576'
        index: 2
        slots: []
      - id: '16927435997720.9140086356603168'
        definitionId: atomicNumber
        styles:
          xl:
            visible: false
        properties:
          name: atomicNumber31
          prop: einldatum
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 3
        slots: []
      - id: '16927435997720.5307600392102809'
        definitionId: atomicNumber
        styles:
          xl:
            visible: false
        properties:
          name: atomicNumber32
          prop: checkplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 4
        slots: []
      - id: '16927435997720.11979791192915301'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString176
          prop: einlieferungplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 5
        slots: []
      - id: '16927435997720.8462075396190007'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString177
          prop: einlieferungsstelle
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 6
        slots: []
      - id: '16927435997720.5706837512578149'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString178
          prop: absender
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 7
        slots: []
      - id: '16927435997720.8717167286943579'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString179
          prop: einlieferer
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 8
        slots: []
      - id: '16927435997720.31148734371280806'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString180
          prop: preadrvariante
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 9
        slots: []
      - id: '16927435997720.41664196329100767'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString181
          prop: preadrid
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 10
        slots: []
      - id: '16927435997720.9771458256651733'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString182
          prop: kilotarif
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 11
        slots: []
      - id: '16927435997720.9662731455681701'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString183
          prop: sendungsart
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 12
        slots: []
      - id: '16927435997720.4672304984251141'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString184
          prop: datamatrix
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: DMC
        parentSlotId: '16927435997720.7686952210888576'
        index: 13
        slots: []
      - id: '16927435997720.26326492104629073'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString185
          prop: image
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 14
        slots: []
      - id: '16927435997720.3129298079231573'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString186
          prop: kuinfofestepos
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 15
        slots: []
      - id: '16927435997720.0070320918421900025'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString187
          prop: labelout
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16927435997720.7686952210888576'
        index: 16
        slots: []
      - id: '16927435997720.8921207730695455'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString188
          prop: brief_nat_ekp
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: EKP
        parentSlotId: '16927435997720.7686952210888576'
        index: 17
        slots: []
      - id: '16927435997720.7130182176328106'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString189
          prop: brief_nat_verfahren
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Verfahren
        parentSlotId: '16927435997720.7686952210888576'
        index: 18
        slots: []
      - id: '16927435997720.349892939606689'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString190
          prop: brief_nat_teilnahme
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Teilnahme
        parentSlotId: '16927435997720.7686952210888576'
        index: 19
        slots: []
      - id: '16927435997720.5780191331012876'
        definitionId: atomicString
        styles: {}
        properties:
          name: atomicString191
          prop: brief_nat_einlieferung
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Einlieferung
        parentSlotId: '16927435997720.7686952210888576'
        index: 20
        slots: []
      - id: '16927435997720.7461310698576717'
        definitionId: atomicString
        styles: {}
        properties:
          name: atomicString192
          prop: brief_nat_buchungstext
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Buchungstext
        parentSlotId: '16927435997720.7686952210888576'
        index: 21
        slots: []
