id: '16927422437510.14679730859326567'
definitionId: smartTable
parentSlotId: '16927412885590.2728932627656391'
styles:
  xl:
    gridItem:
      x: 0
      y: 0
      w: 16
      h: 26
  xs:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 16
properties:
  dynamicColumns:
    value: []
    dataValue: |-
      [
        { prop: 'id', type: 'number', primaryKey: true },
       'full_name',
        { prop: 'avatar', type: 'image' },
        { prop: 'email', type: 'link' },
      ]
    withData: false
  data: '{{actions.loadDboDvfConfig.data}}'
  name: dboDvfConfigTable
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  title: 'Konfiguration Freimachung '
  showLoading:
    withData: true
    dataValue: '{{actions.loadDboDvfConfig.loading}}'
    value: false
  showAddAction:
    value: true
    dataValue: 'false'
    withData: false
  showEditAction:
    value: true
    dataValue: 'false'
    withData: false
  showExportAction:
    value: false
    dataValue: 'true'
    withData: false
  showReloadAction:
    value: true
    dataValue: 'false'
    withData: false
  resetActivePageOnNewData: true
  rowVariation: dense
  showFilter: true
actions:
  init: []
  smartTableCreate: []
  smartTableEdit:
    - action: '16928899495600.9645120455899796'
      paramCode: ''
      blockPageLoad: false
      index: 1
  smartTableBulkEdit: []
  smartTableDelete: []
  smartTableRowSelect: []
  smartTableRowClick: []
  smartTablePageSelect: []
  smartTableFilterChange: []
  smartTableSortChange: []
  smartTableReload: []
index: 0
slots:
  - id: '16927422437510.7944660945297377'
    name: columns
    children:
      - id: '16928913553050.7797674009878073'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString93
          prop: dvfConfigName
          primaryKey: true
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '120'
          filter: true
          title: Config Name
          decoration: null
          pinColumn: left
        index: 0
        slots: []
      - id: '16928913553050.22922560202665965'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString94
          prop: kundenid
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 1
        slots: []
      - id: '16928913553050.9116898869773267'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString95
          prop: optimierung
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '80'
          filter: true
          title: brutto/netto
          sortable: false
          alignment: center
        index: 9
        slots: []
      - id: '16928913553050.7093047448081145'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString96
          prop: einlieferungplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '80'
          filter: true
          title: Einl-PLZ
          alignment: center
        index: 4
        slots: []
      - id: '16928913553050.403796877951635'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 11
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString97
          prop: einlieferungsstelle
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '80'
          filter: true
          title: Einl-Stelle
        index: 5
        slots: []
      - id: '16928913553050.9958584514592468'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString98
          prop: absender
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '100'
          filter: true
          alignment: center
        index: 6
        slots: []
      - id: '16928913553050.25236926656480163'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString99
          prop: einlieferer
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '100'
          filter: true
          alignment: center
        index: 7
        slots: []
      - id: '16928913553050.10395880274613134'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: false
            fontSize:
              customValue: 10
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString100
          prop: preadrvariante
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '60'
          filter: true
        index: 16
        slots: []
      - id: '16928913553050.16182892928916526'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: false
            fontSize:
              customValue: 10
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString101
          prop: preadrid
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '40'
          filter: true
        index: 15
        slots: []
      - id: '16928913553050.09598257177796676'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString102
          prop: kilotarif
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '80'
          filter: true
          title: Kilotarif
          alignment: center
        index: 8
        slots: []
      - id: '16928913553050.6340436431045859'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
        properties:
          name: atomicString103
          prop: sendungsart
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          alignment: center
        index: 3
        slots: []
      - id: '16928913553050.48838629698950364'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString105
          prop: image
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '40'
          filter: true
        index: 12
        slots: []
      - id: '16928913553050.2340323529360684'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString106
          prop: kuinfofestepos
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '40'
          filter: true
        index: 14
        slots: []
      - id: '16928913553050.42213644599252187'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString107
          prop: labelout
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: '40'
          filter: true
        index: 13
        slots: []
      - id: '16928913553050.3885580545757572'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString108
          prop: brief_nat_ekp
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 17
        slots: []
      - id: '16928913553050.21134152703568443'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString109
          prop: brief_nat_verfahren
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 18
        slots: []
      - id: '16928913553050.9671879573643016'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString110
          prop: brief_nat_teilnahme
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 19
        slots: []
      - id: '16928913553050.41516246279325864'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
            visible: true
        properties:
          name: atomicString112
          prop: checkplz
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Check PLZ
          primaryKey: false
          filter: true
          width: '80'
          pinColumn: ''
          alignment: center
        index: 10
        slots: []
      - id: '16928913553050.9293115544824002'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
            visible: true
        properties:
          name: atomicString104
          prop: datamatrix
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Datamatrix
          primaryKey: false
          filter: true
          width: '40'
          alignment: center
        index: 11
        slots: []
      - id: '16928913553050.6687023010936062'
        definitionId: atomicString
        parentSlotId: '16927422437510.7944660945297377'
        styles:
          xl:
            fontSize:
              customValue: 12
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
            visible: true
        properties:
          name: atomicString113
          prop: einldatum
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Einl-Datum
          primaryKey: false
          filter: true
          width: '80'
          alignment: center
        index: 2
        slots: []
