id: '16970590271880.003541497024117213'
definitionId: form
parentSlotId: '16970590271880.38842004910777606'
styles:
  xl:
    gridItem:
      x: 0
      y: 5
      w: 24
      h: 85
  xs:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 80
properties:
  dynamicFields:
    value: []
    dataValue: |-
      [
        { prop: 'id', type: 'number', primaryKey: true },
       'full_name',
        { prop: 'avatar', type: 'image' },
        { prop: 'email', type: 'link' },
      ]
    withData: false
  entity: |
    {{ui.dboDvfConfigTable2.selectedRow.data}}
  name: dbodvfconfigtableForm5
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  title: Brief national (Kontraktinformationen)
  columns: '2'
  submitBtnTitle: Brief national speichern
  showSuccessMessage: true
  successMessage: Kontrakt Brief national gespeichert.
actions:
  init:
    - action: '16970590271900.6701403336771616'
      paramCode: ''
      blockPageLoad: false
      index: 0
  submitEvent:
    - action: '16970590271900.6360023330885893'
      paramCode: ''
      blockPageLoad: false
      index: 1
  formClick: []
  changeEvent: []
  customButtonClick: []
index: 0
slots:
  - id: '16970590271880.026948514015359137'
    name: structure
    children:
      - id: '16970590271890.8204244497955986'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 16
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
            color:
              value: primary
              dataValue: basic
              withData: false
        properties:
          name: atomicString325
          prop: dvfConfigName
          primaryKey: true
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Config Name
          forceView: true
          textStyle:
            transform: none
            styles:
              - bold
        index: 0
        slots: []
      - id: '16970590271890.5902256104353598'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString326
          prop: kunde
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 1
        slots: []
      - id: '16970590271890.4903415705074705'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString327
          prop: optimierung
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: brutto/netto
        index: 2
        slots: []
      - id: '16970590271890.9305593989107708'
        definitionId: atomicNumber
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicNumber52
          prop: einldatum
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        index: 3
        slots: []
      - id: '16970590271890.39891516679408623'
        definitionId: atomicNumber
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicNumber53
          prop: checkplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        index: 4
        slots: []
      - id: '16970590271890.35056743845214755'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString328
          prop: einlieferungplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 5
        slots: []
      - id: '16970590271890.6516210555295794'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString329
          prop: einlieferungsstelle
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 6
        slots: []
      - id: '16970590271890.8656557961176878'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString330
          prop: absender
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 7
        slots: []
      - id: '16970590271890.669051744069245'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString331
          prop: einlieferer
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 8
        slots: []
      - id: '16970590271890.5400863870131996'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString332
          prop: preadrvariante
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 9
        slots: []
      - id: '16970590271890.8961535414848742'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString333
          prop: preadrid
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 10
        slots: []
      - id: '16970590271890.05420152972755754'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString334
          prop: kilotarif
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 11
        slots: []
      - id: '16970590271890.3272245802490834'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString335
          prop: sendungsart
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 12
        slots: []
      - id: '16970590271890.8167210292018983'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString336
          prop: datamatrix
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: DMC
        index: 13
        slots: []
      - id: '16970590271890.45543574834200373'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString337
          prop: image
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 14
        slots: []
      - id: '16970590271890.2073915677974656'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString338
          prop: kuinfofestepos
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 15
        slots: []
      - id: '16970590271890.4106074760734395'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString339
          prop: labelout
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        index: 16
        slots: []
      - id: '16970590271890.5366140405342943'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: true
        properties:
          name: atomicString340
          prop: brief_nat_ekp
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: EKP
        index: 17
        slots: []
      - id: '16970590271890.8233573672003416'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: true
        properties:
          name: atomicString341
          prop: brief_nat_verfahren
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Verfahren
        index: 18
        slots: []
      - id: '16970590271890.792691894555809'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles:
          xl:
            visible: true
        properties:
          name: atomicString342
          prop: brief_nat_teilnahme
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Teilnahme
        index: 19
        slots: []
      - id: '16970590271890.31605795433910044'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles: {}
        properties:
          name: atomicString343
          prop: brief_nat_einlieferung
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Einlieferung
        index: 20
        slots: []
      - id: '16970590271890.8235580068140407'
        definitionId: atomicString
        parentSlotId: '16970590271880.026948514015359137'
        styles: {}
        properties:
          name: atomicString344
          prop: brief_nat_buchungstext
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Buchungstext
        index: 21
        slots: []
