id: '16970590271880.351598984111384'
definitionId: form
parentSlotId: '16970590271880.3111168772122441'
styles:
  xl:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 85
  xs:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 85
properties:
  dynamicFields:
    value: []
    dataValue: |-
      [
        { prop: 'id', type: 'number', primaryKey: true },
       'full_name',
        { prop: 'avatar', type: 'image' },
        { prop: 'email', type: 'link' },
      ]
    withData: false
  entity: |
    {{ui.dboDvfConfigTable2.selectedRow.data}}
  name: dbodvfconfigtableForm7
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  title: Dialogpost national (Kontraktinformationen)
  columns: '2'
actions:
  init: []
  submitEvent: []
  formClick: []
  changeEvent: []
  customButtonClick: []
index: 0
slots:
  - id: '16970590271880.30215298208161134'
    name: structure
    children:
      - id: '16970590271890.9649104937004771'
        definitionId: atomicString
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 16
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
            color:
              value: primary
              dataValue: basic
              withData: false
        properties:
          name: atomicString369
          prop: dvfConfigName
          primaryKey: true
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Config Name
          forceView: true
          textStyle:
            transform: none
            styles:
              - bold
        parentSlotId: '16970590271880.30215298208161134'
        index: 0
        slots: []
      - id: '16970590271890.025049840342773688'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString370
          prop: kunde
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 1
        slots: []
      - id: '16970590271890.5039448069565751'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString371
          prop: optimierung
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: brutto/netto
        parentSlotId: '16970590271880.30215298208161134'
        index: 2
        slots: []
      - id: '16970590271890.40060304193778595'
        definitionId: atomicNumber
        styles:
          xl:
            visible: false
        properties:
          name: atomicNumber56
          prop: einldatum
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 3
        slots: []
      - id: '16970590271890.06831478650938339'
        definitionId: atomicNumber
        styles:
          xl:
            visible: false
        properties:
          name: atomicNumber57
          prop: checkplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 4
        slots: []
      - id: '16970590271890.48157287236358415'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString372
          prop: einlieferungplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 5
        slots: []
      - id: '16970590271890.6300182098014302'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString373
          prop: einlieferungsstelle
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 6
        slots: []
      - id: '16970590271890.827776317444266'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString374
          prop: absender
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 7
        slots: []
      - id: '16970590271890.6734496200350673'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString375
          prop: einlieferer
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 8
        slots: []
      - id: '16970590271890.5062548330349415'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString376
          prop: preadrvariante
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 9
        slots: []
      - id: '16970590271890.3512548251824288'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString377
          prop: preadrid
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 10
        slots: []
      - id: '16970590271890.028516158109632928'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString378
          prop: kilotarif
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 11
        slots: []
      - id: '16970590271890.31253505435120754'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString379
          prop: sendungsart
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 12
        slots: []
      - id: '16970590271890.4565483497843297'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString380
          prop: datamatrix
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: DMC
        parentSlotId: '16970590271880.30215298208161134'
        index: 13
        slots: []
      - id: '16970590271890.01705993746155654'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString381
          prop: image
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 14
        slots: []
      - id: '16970590271890.9075599428828227'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString382
          prop: kuinfofestepos
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 15
        slots: []
      - id: '16970590271890.7303077387602448'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString383
          prop: labelout
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.30215298208161134'
        index: 16
        slots: []
      - id: '16970590271890.08755794390652061'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString384
          prop: dp_ekp
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: EKP
        parentSlotId: '16970590271880.30215298208161134'
        index: 17
        slots: []
      - id: '16970590271890.7226436233035702'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString385
          prop: dp_verfahren
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Verfahren
        parentSlotId: '16970590271880.30215298208161134'
        index: 18
        slots: []
      - id: '16970590271890.13190598009145194'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString386
          prop: dp_teilnahme
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Teilnahme
        parentSlotId: '16970590271880.30215298208161134'
        index: 19
        slots: []
      - id: '16970590271890.04261262147950973'
        definitionId: atomicString
        styles: {}
        properties:
          name: atomicString387
          prop: dp_fertigungsmuster
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Fertigungsmuster
        parentSlotId: '16970590271880.30215298208161134'
        index: 20
        slots: []
      - id: '16970590271890.9582151017998375'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString388
          prop: brief_nat_buchungstext
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Buchungstext
        parentSlotId: '16970590271880.30215298208161134'
        index: 21
        slots: []
