id: '16970600389690.8636316310840602'
definitionId: form
styles:
  xl:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 85
  xs:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 85
properties:
  dynamicFields:
    value: []
    dataValue: |-
      [
        { prop: 'id', type: 'number', primaryKey: true },
       'full_name',
        { prop: 'avatar', type: 'image' },
        { prop: 'email', type: 'link' },
      ]
    withData: false
  entity: |
    {{ui.dboDvfConfigTable3.selectedRow.data}}
  name: dbodvfconfigtableForm9
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  title: Fracht (DHL)
  columns: '2'
parentSlotId: '16970600389690.8493827355123211'
index: 0
actions:
  init: []
  submitEvent: []
  formClick: []
  changeEvent: []
  customButtonClick: []
slots:
  - id: '16970600389690.3339182574386952'
    name: structure
    children:
      - id: '16970600389690.3873852573640344'
        definitionId: atomicString
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 16
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
            color:
              value: primary
              dataValue: basic
              withData: false
        properties:
          name: atomicString178
          prop: dvfConfigName
          primaryKey: true
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Config Name
          forceView: true
          textStyle:
            transform: none
            styles:
              - bold
        parentSlotId: '16970600389690.3339182574386952'
        index: 0
        slots: []
      - id: '16970600389690.002384584895982478'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString179
          prop: kunde
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 1
        slots: []
      - id: '16970600389690.6334226951314761'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString180
          prop: optimierung
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: brutto/netto
        parentSlotId: '16970600389690.3339182574386952'
        index: 2
        slots: []
      - id: '16970600389690.9414895433958286'
        definitionId: atomicNumber
        styles:
          xl:
            visible: false
        properties:
          name: atomicNumber32
          prop: einldatum
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 3
        slots: []
      - id: '16970600389690.5332327988609489'
        definitionId: atomicNumber
        styles:
          xl:
            visible: false
        properties:
          name: atomicNumber60
          prop: checkplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 4
        slots: []
      - id: '16970600389690.2319782316921577'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString181
          prop: einlieferungplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 5
        slots: []
      - id: '16970600389690.11475020784181367'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString182
          prop: einlieferungsstelle
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 6
        slots: []
      - id: '16970600389690.5130229292869548'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString183
          prop: absender
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 7
        slots: []
      - id: '16970600389690.010718395759308885'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString184
          prop: einlieferer
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 8
        slots: []
      - id: '16970600389690.5631452720575232'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString185
          prop: preadrvariante
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 9
        slots: []
      - id: '16970600389690.7948647864936524'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString186
          prop: preadrid
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 10
        slots: []
      - id: '16970600389690.7549073395857311'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString187
          prop: kilotarif
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 11
        slots: []
      - id: '16970600389690.47070992721631444'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString188
          prop: sendungsart
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 12
        slots: []
      - id: '16970600389690.02542745118445411'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString189
          prop: datamatrix
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: DMC
        parentSlotId: '16970600389690.3339182574386952'
        index: 13
        slots: []
      - id: '16970600389690.0029403774263736526'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString190
          prop: image
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 14
        slots: []
      - id: '16970600389690.21449219294879174'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString191
          prop: kuinfofestepos
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 15
        slots: []
      - id: '16970600389690.7463058697844878'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString192
          prop: labelout
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970600389690.3339182574386952'
        index: 16
        slots: []
      - id: '16970600389690.7350108024848356'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString193
          prop: brief_nat_ekp
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: EKP
        parentSlotId: '16970600389690.3339182574386952'
        index: 17
        slots: []
      - id: '16970600389690.9573730460225094'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString194
          prop: brief_nat_verfahren
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Verfahren
        parentSlotId: '16970600389690.3339182574386952'
        index: 18
        slots: []
      - id: '16970600389690.9822760422982642'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString195
          prop: brief_nat_teilnahme
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Teilnahme
        parentSlotId: '16970600389690.3339182574386952'
        index: 19
        slots: []
      - id: '16970600389690.8202036455724697'
        definitionId: atomicString
        styles: {}
        properties:
          name: atomicString196
          prop: brief_nat_einlieferung
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Einlieferung
        parentSlotId: '16970600389690.3339182574386952'
        index: 20
        slots: []
      - id: '16970600389690.6786955202348266'
        definitionId: atomicString
        styles: {}
        properties:
          name: atomicString197
          prop: brief_nat_buchungstext
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Buchungstext
        parentSlotId: '16970600389690.3339182574386952'
        index: 21
        slots: []
