id: '16970590271880.33982887940610573'
definitionId: form
parentSlotId: '16970590271880.7621526696930627'
styles:
  xl:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 85
  xs:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 85
properties:
  dynamicFields:
    value: []
    dataValue: |-
      [
        { prop: 'id', type: 'number', primaryKey: true },
       'full_name',
        { prop: 'avatar', type: 'image' },
        { prop: 'email', type: 'link' },
      ]
    withData: false
  entity: |
    {{ui.dboDvfConfigTable2.selectedRow.data}}
  name: dbodvfconfigtableForm8
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  title: Fracht (DHL)
  columns: '2'
actions:
  init: []
  submitEvent: []
  formClick: []
  changeEvent: []
  customButtonClick: []
index: 0
slots:
  - id: '16970590271880.7905514025032774'
    name: structure
    children:
      - id: '16970590271890.7746894629514074'
        definitionId: atomicString
        styles:
          xl:
            visible: true
            fontSize:
              customValue: 16
              customUnit: px
              themeDefaultOverridePropertyKey: baseTextFontSize
            color:
              value: primary
              dataValue: basic
              withData: false
        properties:
          name: atomicString389
          prop: dvfConfigName
          primaryKey: true
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Config Name
          forceView: true
          textStyle:
            transform: none
            styles:
              - bold
        parentSlotId: '16970590271880.7905514025032774'
        index: 0
        slots: []
      - id: '16970590271890.40916327928684915'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString390
          prop: kunde
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 1
        slots: []
      - id: '16970590271890.2902929655903419'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString391
          prop: optimierung
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: brutto/netto
        parentSlotId: '16970590271880.7905514025032774'
        index: 2
        slots: []
      - id: '16970590271890.1886971083589104'
        definitionId: atomicNumber
        styles:
          xl:
            visible: false
        properties:
          name: atomicNumber58
          prop: einldatum
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 3
        slots: []
      - id: '16970590271890.5450383357698103'
        definitionId: atomicNumber
        styles:
          xl:
            visible: false
        properties:
          name: atomicNumber59
          prop: checkplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 60
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 4
        slots: []
      - id: '16970590271890.21244222562214854'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString392
          prop: einlieferungplz
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 5
        slots: []
      - id: '16970590271890.5542477592940456'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString393
          prop: einlieferungsstelle
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 6
        slots: []
      - id: '16970590271890.7087013790962438'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString394
          prop: absender
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 7
        slots: []
      - id: '16970590271890.9613759287512773'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString395
          prop: einlieferer
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 8
        slots: []
      - id: '16970590271890.8055972518822123'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString396
          prop: preadrvariante
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 9
        slots: []
      - id: '16970590271890.14407624153880216'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString397
          prop: preadrid
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 10
        slots: []
      - id: '16970590271890.19615886776355707'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString398
          prop: kilotarif
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 11
        slots: []
      - id: '16970590271890.37532251642630854'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString399
          prop: sendungsart
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 12
        slots: []
      - id: '16970590271890.0034264711483937837'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString400
          prop: datamatrix
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: DMC
        parentSlotId: '16970590271880.7905514025032774'
        index: 13
        slots: []
      - id: '16970590271890.7040331162536375'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString401
          prop: image
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 14
        slots: []
      - id: '16970590271890.040181725551620584'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString402
          prop: kuinfofestepos
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 15
        slots: []
      - id: '16970590271890.9003756456322758'
        definitionId: atomicString
        styles:
          xl:
            visible: false
        properties:
          name: atomicString403
          prop: labelout
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
        parentSlotId: '16970590271880.7905514025032774'
        index: 16
        slots: []
      - id: '16970590271890.06734847884868644'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString404
          prop: brief_nat_ekp
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: EKP
        parentSlotId: '16970590271880.7905514025032774'
        index: 17
        slots: []
      - id: '16970590271890.24408874346108766'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString405
          prop: brief_nat_verfahren
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Verfahren
        parentSlotId: '16970590271880.7905514025032774'
        index: 18
        slots: []
      - id: '16970590271890.04745282390819838'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString406
          prop: brief_nat_teilnahme
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          width: 120
          filter: true
          title: Teilnahme
        parentSlotId: '16970590271880.7905514025032774'
        index: 19
        slots: []
      - id: '16970590271890.7174938348852318'
        definitionId: atomicString
        styles: {}
        properties:
          name: atomicString407
          prop: brief_nat_einlieferung
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Einlieferung
        parentSlotId: '16970590271880.7905514025032774'
        index: 20
        slots: []
      - id: '16970590271890.6033810535427682'
        definitionId: atomicString
        styles: {}
        properties:
          name: atomicString408
          prop: brief_nat_buchungstext
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          title: Buchungstext
        parentSlotId: '16970590271880.7905514025032774'
        index: 21
        slots: []
